spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    in:
      notyouraveragedev: TRACE
  file: logs/URL-Metrics-Service/URLMetricsServiceLog.log
ip:
  geolocation:
    api:
      key: '{cipher}7b0f8d5f0a2a01512e4c8d046677f087992f0bd2ffcf6f7344a614414e6d6031a0980655ededca3d16c87bdbfbdd674ee7c3902b9a8f66722fb15e8836eefd2c'
