spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url:'jdbc:mysql://13.59.236.75:3306/url_short_db?serverTimezone=Asia/Kolkata'
    username:'{cipher}ba4d898ae162ba997e9406e59d5d32c360b0f52029868c07267c86fef44735ed'
    password:'{cipher}56405b7b66c9e8104b552e63cbf0d0177274a5529e0558b9de2d7e0029227f1c'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    in:
      notyouraveragedev: TRACE
  file: logs/URL-Resolver-Service/URLResolverServiceLog.log
