spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: '{cipher}9d6d103fe13852a5a795386993dcee3d075857211872d4f750513eca0fd641ab9bbe67e8065e496fdfcbd581c02d3c6d18504f5d4b9ba2c9490fe6b4a407387398e36e4e62b738336293b327da841eb1416ae4a8271d23e26dd47d20b162b01e'
    password: '{cipher}1c7c262cc612c6c12b8d322643c967d17a28c3fa58c64f269ef322e16acf417e'
    username: '{cipher}3a45fbb0818ad139f5f6fcfcfeaa68635684010b2674889a65a516494d7b2b8c'


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    in:
      notyouraveragedev: TRACE
  file: logs/URL-Resolver-Service/URLResolverServiceLog.log
